#!/bin/bash

# Define the input file
FOLDER=data/output_31
INFILE=$FOLDER/input.txt
OPFILE=$FOLDER/output.txt

# Read the input file line by line
while read -r LINE
do
  # Print the line to query string
  response=$(curl -G --data-urlencode "text=$LINE" "https://t.song.work/api?from=en&to=mn")
  echo $response | jq -r '.result' >> $OPFILE

  # remove line form input file
  sed '1d' $INFILE > tmpfile; mv tmpfile $INFILE
  # Sleep for 1 second
  sleep 1
done < "$INFILE"