#!/bin/bash

# Define the input file
FOLDER=data
INFILE=$FOLDER/input.txt
OPFILE=$FOLDER/output.txt

# read .env file
ENVS = $(cat .env | grep -v ^# | xargs)
# export .env file
for env in $ENVS; do
  export $env
done

# is not port defined, use default port
if [ -z "$PORT" ]
then
  PORT=8999
fi

# Read the input file line by line
while read -r LINE
do
  # Print the line to query string
  response=$(curl -G --data-urlencode "text=$LINE" "http://127.0.0.1:$PORT/api?from=en&to=mn")
  echo $response | jq -r '.result' >> $OPFILE

  # remove line form input file
  sed '1d' $INFILE > tmpfile; mv tmpfile $INFILE
  # Sleep for 1 second
  sleep 1
done < "$INFILE"