#!/bin/bash

# Define the input file
FOLDER=data
INFILE=$(ls $FOLDER | grep input)
OPFILE=$(ls $FOLDER | grep output)

INFILE=$FOLDER/$INFILE
OPFILE=$FOLDER/$OPFILE

# read .env file
ENVS=$(cat .env | grep -v ^# | xargs)
# export .env file
for env in $ENVS; do
  export $env
done

# is not port defined, use default port
if [ -z "$PORT" ]
then
  PORT=8999
fi

echo "Input file: $INFILE"

# Read the input file line by line
while read -r LINE
do
  { # try
    # Print the line to query string
    response=$(curl -G --data-urlencode "text=$LINE" "http://127.0.0.1:$PORT/api?from=en&to=mn")
    if ["${response}"]; then
      # echo $response | jq -r '.result' >> $OPFILE
      echo 'success'
    else
      echo 'error'
    fi

    # echo $response | jq -r '.result' >> $OPFILE
  } || { # catch
    # Print the line to query string
    echo 'ello'
  }

  # remove line form input file
  sed '1d' $INFILE > tmpfile; mv tmpfile $INFILE
  # Sleep for 1 second
  sleep 1
done < "$INFILE"